# Generated by Django 5.2.5 on 2025-08-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '申请变更历史信息',
                'verbose_name_plural': '申请变更历史信息',
            },
        ),
        migrations.CreateModel(
            name='FieldChangeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('username', '用户名')], max_length=50, verbose_name='字段')),
                ('old_value', models.TextField(verbose_name='旧值')),
                ('new_value', models.TextField(verbose_name='新值')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archived', models.BooleanField(default=False, verbose_name='已归档')),
            ],
            options={
                'verbose_name': '个人信息更改申请',
                'verbose_name_plural': '个人信息更改申请',
            },
        ),
    ]
