# Generated by Django 5.2.5 on 2025-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmessage',
            options={'verbose_name': '申请变更历史信息', 'verbose_name_plural': '申请变更历史信息'},
        ),
        migrations.AlterModelOptions(
            name='fieldchangeapplication',
            options={'verbose_name': '个人信息更改申请', 'verbose_name_plural': '个人信息更改申请'},
        ),
        migrations.RemoveField(
            model_name='fieldchangeapplication',
            name='admin_comment',
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='field_name',
            field=models.CharField(choices=[('salary', '薪资(RMB)'), ('phone', '手机'), ('photo', '照片')], max_length=50),
        ),
    ]
