# Generated by Django 5.2.5 on 2025-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicationmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldchangeapplication',
            name='old_value',
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='field_name',
            field=models.CharField(choices=[('salary', '薪资(RMB)')], max_length=50),
        ),
    ]
