# Generated by Django 5.2.5 on 2025-08-28 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_fieldchangeapplication_old_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmessage',
            name='approval_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approval_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
