# Generated by Django 5.2.5 on 2025-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_applicationmessage_approval_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchangeapplication',
            name='old_value',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
