# Generated by Django 5.2.5 on 2025-08-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_fieldchangeapplication_old_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchangeapplication',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
