# Generated by Django 5.2.5 on 2025-08-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_fieldchangeapplication_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='application.fieldchangeapplication', verbose_name='申请'),
        ),
        migrations.AlterField(
            model_name='applicationmessage',
            name='approval_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_user', to=settings.AUTH_USER_MODEL, verbose_name='审批用户'),
        ),
        migrations.AlterField(
            model_name='applicationmessage',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='applicationmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='applicationmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='已归档'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='field_name',
            field=models.CharField(choices=[('salary', '薪资(RMB)')], max_length=50, verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='new_value',
            field=models.TextField(verbose_name='新值'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='old_value',
            field=models.TextField(verbose_name='旧值'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
