# Generated by Django 5.2.5 on 2025-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_applicationmessage_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldchangeapplication',
            name='field_name',
            field=models.CharField(choices=[('username', '用户名')], max_length=50, verbose_name='字段'),
        ),
    ]
