# Generated by Django 5.2.5 on 2025-08-28 14:09

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user/photos/default.png', upload_to=user.models.user_photo_upload_to, verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='薪资(RMB)'),
        ),
    ]
