# Generated by Django 5.2.5 on 2025-08-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
