# Generated by Django 5.2.5 on 2025-08-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('reset_password', '可以重置用户密码为123456')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
